### ISSUE TITLE
Looks great

### ISSUE THREAD

**Issue by georgebastille** [ajosephides/guessthemovie#2]
Safe, it looks great.
Generla comment. Code style is a very subjective thing, ususally you work to the standard set by your peers. If you are working on your own you get free reign. Best thing is to decide on a style you like and then to be consistent. Things like:
When writing s method, should the { be on the same link as the method or the next line?
How many newlines before/after a method/class?
White space around conditional flow elements (if, else, switch...)
One option with this is to use a tool, you can download code styles from e.g. Google and run the tool and it will make your code look nice. Google Java Code Formatter to find some.

 I have a few specific questions:
Game.java:
1. Please correct indentation, make it harder to read when indent levels are off.
2. Please group public and private methods togerther, I put public methods first and private last, but that is a personal choice (e.g. https://softwareengineering.stackexchange.com/questions/186418/in-java-should-private-helpers-go-above-or-below-public-methods)
3. Please set all private variables to a default value in the constructor.
4. Please remove unecessary new lines.

Movie.java
1. Static methods are associated with the Class definition, and not any specific instansiation of the class. As such, they can only access static fields in the class (and any arguments passed to them). The static methods here don't access any of the object members. This suggests that there may be a design issue here. It is worth thinking about what each object does, what it contains and what the outside world need to know about it. Acvtually, all your static methods are private helper methods, which is probably fine.

One example, it might make sense for main to create a Game object, and inside that game object, it creates a Movie object. Now, main interacts solely though the public methods of Game, and does not know about Movie at all. This should simplify main, reduce the number of parameters you pass around.

**Comment by ajosephides** [comment]
Can seem to add you as a reviewer to the request.
https://github.com/ajosephides/guessthemovie/pull/4

**Comment by ajosephides** [comment]
Can seem to add you as a reviewer to the request.
https://github.com/ajosephides/guessthemovie/pull/4

**Comment by ajosephides** [comment]
Can seem to add you as a reviewer to the request.
https://github.com/ajosephides/guessthemovie/pull/4
